# Generated by Django 5.1.4 on 2025-04-25 09:54

import app01.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('sex', models.CharField(max_length=4, verbose_name='性别')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('tel', models.CharField(max_length=64, verbose_name='联系方式')),
                ('permissions_project', models.CharField(blank=True, max_length=256, null=True, verbose_name='available_pro')),
            ],
        ),
        migrations.CreateModel(
            name='LmsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('project', '项目管理'), ('delivery', '递送'), ('modify', '修饰'), ('guest', '访客'), ('superadmin', '超级管理员'), ('admin', '管理员'), ('data_admin', '数据库管理员')], default='guest', max_length=20, verbose_name='用户类型')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('permissions_project', models.CharField(blank=True, max_length=256, null=True, verbose_name='可查看的项目号')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('rm_code', models.CharField(default=app01.models.generate_random_code, max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='RM_Code')),
                ('seq', models.CharField(max_length=100, null=True, verbose_name='Sequence')),
                ('seq_type', models.CharField(choices=[('duplex', 'Duplex'), ('AS', 'AS'), ('SS', 'SS')], max_length=10, verbose_name='Sequence Type')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
            ],
            options={
                'indexes': [models.Index(fields=['seq'], name='app01_seque_seq_63205c_idx'), models.Index(fields=['seq_type'], name='app01_seque_seq_typ_279ef1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeqInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(max_length=100, null=True, verbose_name='Sequence')),
                ('Target', models.CharField(max_length=64, null=True, verbose_name='Target')),
                ('Pos', models.CharField(max_length=64, null=True, verbose_name='Pos')),
                ('Transcript', models.CharField(max_length=64, null=True, verbose_name='Transcription')),
                ('parents', models.CharField(max_length=200, null=True, verbose_name='parents')),
                ('Remark', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_info', to='app01.sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.CharField(default=app01.models.generate_random_code, max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('modify_seq', models.CharField(max_length=100, null=True, verbose_name='modify_seq')),
                ('linker_seq', models.CharField(max_length=100, null=True, verbose_name='linker_seq')),
                ('naked_length', models.CharField(max_length=100, null=True, verbose_name='Naked Length')),
                ('delivery5', models.CharField(max_length=100, null=True, verbose_name='Delivery5')),
                ('delivery3', models.CharField(max_length=100, null=True, verbose_name='Delivery3')),
                ('Strand_MWs', models.CharField(max_length=64, null=True, verbose_name='Strand_MWs')),
                ('project', models.CharField(max_length=64, null=True, verbose_name='项目')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('Remark', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Remark')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='app01.sequence')),
            ],
        ),
        migrations.CreateModel(
            name='DuplexRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('as_seq', models.ForeignKey(limit_choices_to={'seq_type': 'AS'}, on_delete=django.db.models.deletion.CASCADE, related_name='as_sequences', to='app01.sequence')),
                ('duplex_seq', models.ForeignKey(limit_choices_to={'seq_type': 'duplex'}, on_delete=django.db.models.deletion.CASCADE, related_name='duplex_sequences', to='app01.sequence')),
                ('ss_seq', models.ForeignKey(limit_choices_to={'seq_type': 'SS'}, on_delete=django.db.models.deletion.CASCADE, related_name='ss_sequences', to='app01.sequence')),
            ],
            options={
                'unique_together': {('as_seq', 'ss_seq')},
            },
        ),
    ]
