# Generated by Django 5.1.4 on 2026-06-07 21:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('compound_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('project', models.CharField(blank=True, db_index=True, max_length=32)),
                ('target', models.CharField(blank=True, db_index=True, max_length=32)),
                ('transcript_ref', models.CharField(blank=True, max_length=64)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compound',
                'ordering': ['compound_id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=64)),
                ('type_code', models.CharField(blank=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'delivery_module',
            },
        ),
        migrations.CreateModel(
            name='LinkerModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'linker_module',
            },
        ),
        migrations.CreateModel(
            name='SeqModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=64)),
                ('base_char', models.CharField(blank=True, max_length=8)),
                ('linker_connector', models.CharField(blank=True, max_length=4)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'seq_module',
            },
        ),
        migrations.CreateModel(
            name='LmsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('guest', 'guest'), ('delivery', 'delivery'), ('modify', 'modify'), ('project', 'project'), ('data_admin', 'data_admin'), ('admin', 'admin'), ('superadmin', 'superadmin')], default='guest', max_length=20)),
                ('permissions_project', models.TextField(blank=True, default='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'lms_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_type', models.CharField(choices=[('in_vitro', '体外'), ('in_vivo', '体内')], max_length=16)),
                ('assay_name', models.CharField(max_length=128)),
                ('cell_line', models.CharField(blank=True, max_length=64)),
                ('batch_label', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='app01.compound')),
            ],
            options={
                'db_table': 'experiment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.FloatField()),
                ('x_type', models.CharField(choices=[('concentration', '浓度 nM'), ('timepoint', '时间点 天')], max_length=16)),
                ('replicate', models.CharField(max_length=8)),
                ('value', models.FloatField()),
                ('readout_type', models.CharField(max_length=32)),
                ('is_control', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_note', models.CharField(blank=True, max_length=128)),
                ('raw_cp', models.JSONField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='app01.experiment')),
            ],
            options={
                'db_table': 'data_point',
            },
        ),
        migrations.CreateModel(
            name='ExperimentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_kd_pct', models.FloatField(blank=True, null=True)),
                ('ic50_nm', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='app01.experiment')),
            ],
            options={
                'db_table': 'experiment_summary',
            },
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand_type', models.CharField(choices=[('SS', 'Sense'), ('AS', 'Antisense')], max_length=4)),
                ('sequence_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('modify_seq', models.TextField(blank=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='app01.compound')),
            ],
            options={
                'db_table': 'strand',
                'unique_together': {('compound', 'strand_type')},
            },
        ),
    ]
