# Generated by Django 5.1.4 on 2025-04-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seqinfo',
            name='project',
            field=models.CharField(max_length=64, null=True, verbose_name='项目'),
        ),
    ]
