# Generated by Django 5.1.4 on 2025-05-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_seqinfo_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seqinfo',
            name='parents',
        ),
        migrations.AddField(
            model_name='delivery',
            name='parents',
            field=models.CharField(max_length=200, null=True, verbose_name='parents'),
        ),
    ]
