# Generated by Django 5.1.4 on 2026-06-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_experiment_animal_species_experiment_animal_strain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='target_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
