# Generated by Django 5.1.4 on 2025-05-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_seqinfo_parents_delivery_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seqinfo',
            name='Target',
        ),
        migrations.AddField(
            model_name='delivery',
            name='Target',
            field=models.CharField(max_length=64, null=True, verbose_name='Target'),
        ),
    ]
