# Generated by Django 5.1.4 on 2026-06-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_add_compound_target_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='target_name',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
