# Generated by Django 5.1.4 on 2026-06-17 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_add_target_name_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(db_index=True, max_length=32)),
                ('label', models.CharField(max_length=128)),
                ('vocab_code', models.CharField(blank=True, default='', max_length=64)),
                ('file', models.FileField(upload_to='project_attachments/%Y%m%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_attachment',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('file_type', '文件类型'), ('invivo_readout', '体内 readout')], db_index=True, max_length=32)),
                ('code', models.SlugField(allow_unicode=True, max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('is_builtin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'upload_vocabulary',
                'ordering': ['category', '-is_builtin', 'label'],
                'unique_together': {('category', 'code')},
            },
        ),
    ]
