# Generated by Django 5.1.4 on 2025-05-19 16:03

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_seqinfo_target_delivery_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='duplex_id',
            field=models.CharField(max_length=6, null=True, verbose_name='duplex_id'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.CharField(default=app01.models.generate_random_code, max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
