# Generated by Django 5.1.4 on 2025-05-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_delivery_duplex_id_alter_delivery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='seq_type',
            field=models.CharField(max_length=6, null=True, verbose_name='seq_type'),
        ),
    ]
