# Generated by Django 5.1.4 on 2025-05-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_delivery_seq_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='duplex_id',
            field=models.CharField(max_length=24, null=True, verbose_name='duplex_id'),
        ),
    ]
