# Generated by Django 5.1.4 on 2026-06-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_seed_upload_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattachment',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
