# Generated by Django 5.1.4 on 2025-06-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_delivery_duplex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
