# Generated by Django 5.1.4 on 2026-06-23

from django.db import migrations


def cleanup_vocab(apps, schema_editor):
    UploadVocabulary = apps.get_model('app01', 'UploadVocabulary')
    # Delete the user-added non-builtin duplicate
    UploadVocabulary.objects.filter(
        category='file_type', code='转染', is_builtin=False
    ).delete()
    # Rename the builtin entry's label
    UploadVocabulary.objects.filter(
        category='file_type', code='vitro_transfection', is_builtin=True
    ).update(label='转染')


def reverse_vocab(apps, schema_editor):
    UploadVocabulary = apps.get_model('app01', 'UploadVocabulary')
    UploadVocabulary.objects.filter(
        category='file_type', code='vitro_transfection', is_builtin=True
    ).update(label='转染方案')


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_add_schedule_to_experiment'),
    ]

    operations = [
        migrations.RunPython(cleanup_vocab, reverse_vocab),
    ]
