# Generated by Django 5.1.4 on 2025-06-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_delivery_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color_type', models.CharField(default='unknown', max_length=10)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
