# Generated by Django 5.1.4 on 2025-06-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_deliverycomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('type_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DeliveryComponent',
        ),
    ]
