# Generated by Django 5.1.4 on 2025-06-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_deliverymodule_delete_deliverycomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodule',
            name='color',
            field=models.CharField(default='#CACACA', max_length=7),
        ),
    ]
