# Generated by Django 5.1.4 on 2026-06-25 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_permission_redesign'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_log',
        ),
        migrations.AlterModelTable(
            name='projectaccessrequest',
            table='project_access_request',
        ),
    ]
