# Generated by Django 5.1.4 on 2025-06-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_deliverymodule_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymodule',
            name='color',
            field=models.CharField(blank=True, default='#CACACA', max_length=7),
        ),
        migrations.AlterField(
            model_name='deliverymodule',
            name='type_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
