# Generated by Django 5.1.4 on 2025-06-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_alter_deliverymodule_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymodule',
            name='color',
        ),
    ]
