# Generated by Django 5.1.4 on 2026-06-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_experiment_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='batch_label',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
