# Generated by Django 5.1.4 on 2025-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_deliverymodule_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymodule',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
