# Generated by Django 5.1.4 on 2026-06-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_add_batch_label_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsuser',
            name='edit_projects',
            field=models.TextField(blank=True, default='', help_text='逗号分隔的可编辑 project_code'),
        ),
        migrations.AddField(
            model_name='projectaccessrequest',
            name='request_type',
            field=models.CharField(choices=[('view', '查看权限'), ('edit', '编辑权限')], default='view', max_length=8),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('register', '注册'), ('project_request', '申请项目'), ('project_approved', '项目批准'), ('project_rejected', '项目拒绝'), ('user_role_changed', '角色变更'), ('user_deleted', '用户删除'), ('edit_request', '申请编辑权限'), ('edit_approved', '编辑权限批准'), ('edit_rejected', '编辑权限拒绝')], max_length=32),
        ),
    ]
