# Generated by Django 5.1.4 on 2025-06-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_alter_deliverymodule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymodule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
