# Generated by Django 5.1.4 on 2025-06-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_alter_deliverymodule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodule',
            name='Strand_MWs',
            field=models.CharField(max_length=64, null=True, verbose_name='Strand_MWs'),
        ),
    ]
