# Generated by Django 5.1.4 on 2025-06-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_deliverymodule_strand_mws'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_id',
            field=models.CharField(max_length=20, null=True, verbose_name='Delivery ID'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
