# Generated by Django 5.1.4 on 2025-07-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_delivery_delivery_id_alter_delivery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='linker_seq',
            field=models.CharField(max_length=500, null=True, verbose_name='linker_seq'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='modify_seq',
            field=models.CharField(max_length=500, null=True, verbose_name='modify_seq'),
        ),
    ]
