# Generated by Django 5.1.4 on 2026-04-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_alter_delivery_linker_seq_alter_delivery_modify_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeqModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('base_char', models.CharField(blank=True, max_length=10, null=True)),
                ('linker_connector', models.CharField(default='o', max_length=2)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
