# Generated by Django 5.1.4 on 2026-04-07 09:56

from django.db import migrations

# (keyword, base_char, linker_connector)
# base_char=None → 纯连接符，无对应裸碱基
SEQMODULE_DATA = [
    # ── 4-char GNA 系列（GA/GU/GC/GG + 数字） ──────────────────────────────
    ('GA02', 'A', 'o'), ('GC02', 'C', 'o'), ('GU02', 'U', 'o'),
    ('GA25', 'A', 'o'), ('GU25', 'U', 'o'), ('GC25', 'C', 'o'), ('GG25', 'G', 'o'),
    ('GA30', 'A', 'o'), ('GU30', 'U', 'o'),
    ('GU05', 'U', 'o'), ('GU10', 'U', 'o'), ('GU13', 'U', 'o'), ('GU14', 'U', 'o'),
    ('GU16', 'U', 'o'), ('GU18', 'U', 'o'), ('GU19', 'U', 'o'), ('GU20', 'U', 'o'),
    ('GU27', 'U', 'o'), ('BU01', 'U', 'o'),
    # ── 4-char TNA 系列（TA/TC/TG/TU + 数字） ──────────────────────────────
    ('TA12', 'A', 'o'), ('TC12', 'C', 'o'), ('TG12', 'G', 'o'), ('TU02', 'U', 'o'),
    # ── VP 系列 ─────────────────────────────────────────────────────────────
    ('VP25A', 'A', 'o'),
    ('VP25',  'U', 'o'), ('VP34', 'U', 'o'), ('VP36', 'U', 'o'), ('VP37', 'U', 'o'),
    ('VP41',  'A', 'o'), ('VP43', 'A', 'o'), ('VP44', 'A', 'o'), ('VP45', 'A', 'o'),
    ('VPAm',  'A', 'o'), ('VPUm', 'U', 'o'),
    ('VPAM',  'A', 'o'), ('VPUM', 'U', 'o'),
    # ── 括号修饰：T(MOE)/T(LNA) → U；A/U/G/C(MOE/LNA/OCF3) ────────────────
    ('T(MOE)', 'U', 'o'), ('T(LNA)', 'U', 'o'),
    ('A(MOE)', 'A', 'o'), ('U(MOE)', 'U', 'o'), ('C(MOE)', 'C', 'o'), ('G(MOE)', 'G', 'o'),
    ('A(LNA)', 'A', 'o'), ('U(LNA)', 'U', 'o'), ('C(LNA)', 'C', 'o'), ('G(LNA)', 'G', 'o'),
    ('A(OCF3)', 'A', 'o'), ('U(OCF3)', 'U', 'o'), ('C(OCF3)', 'C', 'o'), ('G(OCF3)', 'G', 'o'),
    # ── 3-char 杂项 ─────────────────────────────────────────────────────────
    ('TU0', 'U', 'o'), ('TU', 'U', 'o'), ('DT', 'U', 'o'),
    ('C16', 'C', 'o'), ('G16', 'G', 'o'), ('A16', 'A', 'o'),
    ('U22', 'U', 'o'), ('Uy1', 'U', 'o'), ('B04', 'A', 'o'),
    ('U92', 'U', 'o'), ('C92', 'C', 'o'), ('G92', 'G', 'o'), ('A92', 'A', 'o'),
    # ── n 系列 ──────────────────────────────────────────────────────────────
    ('An1', 'A', 'o'), ('Cn1', 'C', 'o'),
    ('An2', 'A', 'o'), ('Gn2', 'G', 'o'), ('Cn2', 'C', 'o'), ('Un2', 'U', 'o'),
    ('Un16', 'U', 'o'),
    # ── dNTP 系列 ───────────────────────────────────────────────────────────
    ('dA', 'A', 'o'), ('dT', 'U', 'o'), ('dG', 'G', 'o'), ('dC', 'C', 'o'), ('dU', 'U', 'o'),
    # ── 2-char 修饰核苷（2'-O-methyl / 2'-fluoro） ──────────────────────────
    ('Am', 'A', 'o'), ('Cm', 'C', 'o'), ('Um', 'U', 'o'), ('Gm', 'G', 'o'),
    ('Af', 'A', 'o'), ('Cf', 'C', 'o'), ('Uf', 'U', 'o'), ('Gf', 'G', 'o'),
    # ── INVAB（反义碱基） ────────────────────────────────────────────────────
    ('INVAB', 'INVAB', 'o'),
    # ── 单字符修饰后缀（m/f 需加 o；I=肌苷） ────────────────────────────────
    ('m', None, 'o'),
    ('f', None, 'o'),
    ('I', 'I', 'o'),
    # ── 纯连接符（追加 '-'，无裸碱基） ──────────────────────────────────────
    ('P91', None, '-'), ('LK1', None, '-'), ('P93', None, '-'), ('P96', None, '-'),
]


def seed_seqmodule(apps, schema_editor):
    SeqModule = apps.get_model('app01', 'SeqModule')
    for keyword, base_char, linker_connector in SEQMODULE_DATA:
        SeqModule.objects.get_or_create(
            keyword=keyword,
            defaults={'base_char': base_char, 'linker_connector': linker_connector},
        )


def unseed_seqmodule(apps, schema_editor):
    SeqModule = apps.get_model('app01', 'SeqModule')
    keywords = [row[0] for row in SEQMODULE_DATA]
    SeqModule.objects.filter(keyword__in=keywords).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_add_seqmodule'),
    ]

    operations = [
        migrations.RunPython(seed_seqmodule, reverse_code=unseed_seqmodule),
    ]
