# Generated by Django 5.1.4 on 2026-04-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_seed_seqmodule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
