# Generated by Django 5.1.4 on 2026-04-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_remove_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seqinfo',
            name='seq',
        ),
    ]
