# Generated by Django 5.1.4 on 2026-04-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_remove_seqinfo_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='Remark',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='seqinfo',
            name='Pos',
            field=models.CharField(max_length=512, null=True, verbose_name='Pos'),
        ),
        migrations.AlterField(
            model_name='seqinfo',
            name='Remark',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='seqinfo',
            name='Transcript',
            field=models.CharField(max_length=512, null=True, verbose_name='Transcription'),
        ),
        migrations.AlterField(
            model_name='seqinfo',
            name='project',
            field=models.CharField(max_length=128, null=True, verbose_name='项目'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['project', 'duplex_id'], name='idx_delivery_project_duplex'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['project'], name='idx_delivery_project'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['sequence', 'seq_type'], name='idx_delivery_seq_seqtype'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery5', 'delivery3', 'linker_seq'], name='idx_delivery_dedup'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['duplex_id'], name='idx_delivery_duplex_id'),
        ),
        migrations.AddIndex(
            model_name='sequence',
            index=models.Index(fields=['seq', 'seq_type'], name='idx_sequence_seq_seqtype'),
        ),
    ]
