# Generated by Django 5.1.4 on 2026-05-13 22:03

import django.db.models.deletion
from django.db import migrations, models


def backfill_delivery_projects(apps, schema_editor):
    Delivery = apps.get_model('app01', 'Delivery')
    DeliveryProject = apps.get_model('app01', 'DeliveryProject')
    objs = []
    for d in Delivery.objects.exclude(project__isnull=True).exclude(project=''):
        objs.append(DeliveryProject(delivery=d, project_code=d.project))
    DeliveryProject.objects.bulk_create(objs, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_add_indexes_and_expand_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='app01.delivery')),
            ],
            options={
                'indexes': [models.Index(fields=['project_code'], name='app01_deliv_project_de4ae1_idx'), models.Index(fields=['delivery'], name='app01_deliv_deliver_7d436d_idx')],
                'unique_together': {('delivery', 'project_code')},
            },
        ),
        migrations.RunPython(backfill_delivery_projects, migrations.RunPython.noop),
    ]
