# Generated by Django 5.1.4 on 2026-05-29 13:11

from django.db import migrations, models


def backfill_y2325_default(apps, schema_editor):
    """Set default_seq_type='AS' for Y2325 user (previously hardcoded)."""
    LmsUser = apps.get_model('app01', 'LmsUser')
    LmsUser.objects.filter(username='Y2325').update(default_seq_type='AS')


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0032_sequence_seq_maxlen'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsuser',
            name='default_seq_type',
            field=models.CharField(choices=[('SS', 'SS'), ('AS', 'AS')], default='SS', max_length=10, verbose_name='默认序列方向'),
        ),
        migrations.RunPython(backfill_y2325_default, migrations.RunPython.noop),
    ]
