# Generated by Django 5.1.4 on 2026-05-30 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_roles_and_module_perms(apps, schema_editor):
    """Remap old 7-level user_type to new 3-level; backfill module_permissions
    for users who were data_admin (they had full module access before)."""
    LmsUser = apps.get_model('app01', 'LmsUser')

    # Step 1: grant full module permissions to former data_admins BEFORE we
    # overwrite their user_type (so we can still identify them).
    LmsUser.objects.filter(user_type='data_admin').update(
        module_permissions='delivery,seq,linker'
    )

    # Step 2: remap all user_type values
    role_map = {
        'superadmin': 'superadmin',
        'admin':      'superadmin',
        'data_admin': 'sub_admin',
        'project':    'user',
        'modify':     'user',
        'delivery':   'user',
        'guest':      'user',
    }
    for old, new in role_map.items():
        LmsUser.objects.filter(user_type=old).update(user_type=new)


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0033_lmsuser_default_seq_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsuser',
            name='module_permissions',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='模块管理权限'),
        ),
        migrations.AlterField(
            model_name='lmsuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否为管理员 (deprecated)'),
        ),
        migrations.AlterField(
            model_name='lmsuser',
            name='user_type',
            field=models.CharField(choices=[('superadmin', '超级管理员'), ('sub_admin', '次级管理员'), ('user', '普通用户')], default='user', max_length=16, verbose_name='用户类型'),
        ),
        migrations.CreateModel(
            name='ProjectAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_codes', models.CharField(max_length=512, verbose_name='申请项目号')),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='申请说明')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=16, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('review_note', models.CharField(blank=True, max_length=256, verbose_name='审批备注')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '项目权限申请',
                'verbose_name_plural': '项目权限申请',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.RunPython(
            migrate_roles_and_module_perms,
            migrations.RunPython.noop,
        ),
    ]
