# Generated by Django 5.1.4 on 2026-05-30 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0034_permission_redesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules_requested', models.CharField(max_length=64, verbose_name='申请模块')),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='申请说明')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=16, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('review_note', models.CharField(blank=True, max_length=256, verbose_name='审批备注')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_module_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '模块权限申请',
                'verbose_name_plural': '模块权限申请',
                'ordering': ['-requested_at'],
            },
        ),
    ]
