# Generated by Django 5.1.4 on 2026-06-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0035_module_permission_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
    ]
