# Generated by Django 5.1.4 on 2026-06-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0036_sequence_created_at_auto_now_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='readout_type',
            field=models.CharField(max_length=32, verbose_name='终点类型'),
        ),
    ]
